version: '3'
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: