version: '3'
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: